### ISSUE TITLE
Not showing my IP

### ISSUE THREAD

**Issue by tlugger** [thedmeyer/DuhMyIP#31]
![screen shot 2017-10-02 at 8 37 37 pm](https://user-images.githubusercontent.com/10581772/31107724-b76d7672-a7b1-11e7-9a1e-080fcb79d1cf.png)

Using Chrome with both HTTP and HTTPS.

**Comment by LRFLEW** [comment]
Same in Safari. Firefox is working for me, though.

**Comment by LRFLEW** [comment]
@tlugger Do you happen to have an ad blocker on? I realized that uBlock Origin (with default filters) blocks ipify.org, which prevents this from working. While this should have some more error-checking for this kind of thing, this doesn't appear to be an error with the website (or, at least, not one that I was able to recreate).

I did discover another issue (particularly with Safari), which I will open another issue for.

**Comment by mehlleniumfalke** [comment]
I had the same issue with uBlockOrigin.
Deactivation helped out so far.

**Comment by tlugger** [comment]
Good catch @LRFLEW. That solved my issue!
