### ISSUE TITLE
ES6 refactor

### ISSUE THREAD

**Issue by TheMyopist** [thedmeyer/DuhMyIP#38]
Hey, would you like me to refactor your code to ES6?

- const/let
- arrow functions
- concat
- ...

Would be a good training for me.

**Comment by jhia** [comment]
Remember to refactor and also add a script to transform code from ES6+ to ES5, for compatibility reasons 😸  and call the bundle inside `index.html`. Happy coding!

**Comment by thedmeyer** [comment]
@TheMyopist Have at it!
