### ISSUE TITLE
None of the sounds load when I try to duh my IP

### ISSUE THREAD

**Issue by coulterpeterson** [thedmeyer/DuhMyIP#43]
I only get sound from the live site if I click the face, but no IP dumbification. I've got a cool addition idea, but not sure if there's functionality I could help fix first.

**Comment by thedmeyer** [comment]
Is your IP showing? If not, could be an ad blocker

https://github.com/thedmeyer/DuhMyIP/issues/31

**Comment by coulterpeterson** [comment]
That was totally it - will look into adding an ad blocker notification and submitting a pull request for it. Thanks!
